### ISSUE TITLE
Resultados segundo turno

### ISSUE THREAD

**Issue by Argonalyst** [marcofaga/eleicoes2020#1]
Olá. Alguma atualização sobre os resultados do segundo turno? Nem mesmo os arquivos do repositório do TSE possuem o resultado final do segundo turno.. muito bizarro, eles simplesmente divulgam a situação final como "2º TURNO" sem especificar se o candidato foi eleito ou não (no segundo turno).

**Comment by marcofaga** [comment]
Olá. Eu decidi não atualizar mais pensando exatamente que teria tudo no repositório do TSE. Quando o resultado final do primeiro turno for segundo turno, eles indicam como resultado final como "2 TURNO" mesmo. Aí tem uma variável indicando se a eleição é de segundo ou primeiro turno. E lá sim tem o resultado final daquele turno. Você viu isso?

**Comment by Argonalyst** [comment]
Verdade, agora percebi que eles inseriram uma nova linha repetindo o candidato e alterando a variável da situação, todos os candidatos que foram para segundo turno estão repetidos. Obrigado pela observação!
